### ISSUE TITLE
calculating linkrange is wrong

### ISSUE THREAD

**Issue by otus-scops** [c2nprds/hubot-ingress-linkrange#1]
linkrange is 160km_(average ^4) is true
but, this average uses in after the decimal point
this script used in Truncation point below
`average     = Math.floor(total/8)
baseRange   = 160_Math.pow(average, 4)`

I think, Correctly , it will be following
`average     = Math.floor(total/8)
baseRange   = 160*Math.pow(total/8, 4)`

**Comment by c2nprds** [comment]
thanks @otus-scops! :)
